all:
	echo $(shell basename $(CURDIR))
	npm run start -- --only $(shell basename $(CURDIR))

reload:
	echo $(shell basename $(CURDIR))
	npm run reload -- --only $(shell basename $(CURDIR))

show:
	echo $(shell basename $(CURDIR))
	npm run show -- $(shell basename $(CURDIR))

status:
	npm run status

stop:
	echo $(shell basename $(CURDIR))
	npm run stop -- $(shell basename $(CURDIR))
