# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_trials 1'] = {
    'completed_demographics': False,
    'consent_agreed': False,
    'num_trials': 84,
    'trials': [
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '25',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 1,
            'word': 'body vs capital',
            'word1_en': 'body',
            'word2_en': 'capital'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '49',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 2,
            'word': 'cypress vs sun',
            'word1_en': 'cypress',
            'word2_en': 'sun'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '27',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 3,
            'word': 'unsophisticated vs wood',
            'word1_en': 'unsophisticated',
            'word2_en': 'wood'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '76',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 4,
            'word': 'attachment vs stretch',
            'word1_en': 'attachment',
            'word2_en': 'stretch'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '10',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 5,
            'word': 'boost vs offer',
            'word1_en': 'boost',
            'word2_en': 'offer'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '77',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 6,
            'word': 'handsome vs quiet',
            'word1_en': 'handsome',
            'word2_en': 'quiet'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '30',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 7,
            'word': 'general vs float',
            'word1_en': 'general',
            'word2_en': 'float'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '45',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 8,
            'word': 'sofa vs change',
            'word1_en': 'sofa',
            'word2_en': 'change'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '38',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 9,
            'word': 'chair vs river',
            'word1_en': 'chair',
            'word2_en': 'river'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '61',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 10,
            'word': 'hurt vs guess',
            'word1_en': 'hurt',
            'word2_en': 'guess'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '2',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 11,
            'word': 'cloudy vs moon',
            'word1_en': 'cloudy',
            'word2_en': 'moon'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '12',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 12,
            'word': 'covenant vs knife',
            'word1_en': 'covenant',
            'word2_en': 'knife'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '43',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 13,
            'word': 'comb vs cultivate',
            'word1_en': 'comb',
            'word2_en': 'cultivate'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '9',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 14,
            'word': 'forthright vs stone',
            'word1_en': 'forthright',
            'word2_en': 'stone'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '24',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 15,
            'word': 'frequently vs step',
            'word1_en': 'frequently',
            'word2_en': 'step'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '78',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 16,
            'word': 'fat vs lamp',
            'word1_en': 'fat',
            'word2_en': 'lamp'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '62',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 17,
            'word': 'run vs ugly',
            'word1_en': 'run',
            'word2_en': 'ugly'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '28',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 18,
            'word': 'miscellaneous vs silk thread',
            'word1_en': 'miscellaneous',
            'word2_en': 'silk thread'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '23',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 19,
            'word': 'basic vs soil',
            'word1_en': 'basic',
            'word2_en': 'soil'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '46',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 20,
            'word': 'science vs rent',
            'word1_en': 'science',
            'word2_en': 'rent'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '6',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 21,
            'word': 'rigid vs woods',
            'word1_en': 'rigid',
            'word2_en': 'woods'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '13',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 22,
            'word': 'adopt vs grasp',
            'word1_en': 'adopt',
            'word2_en': 'grasp'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '53',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 23,
            'word': ' basic  vs china bowl',
            'word1_en': ' basic ',
            'word2_en': 'china bowl'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '26',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 24,
            'word': 'levels vs cloud',
            'word1_en': 'levels',
            'word2_en': 'cloud'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '51',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 25,
            'word': 'literature vs neat',
            'word1_en': 'literature',
            'word2_en': 'neat'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '36',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 26,
            'word': 'key vs muscle',
            'word1_en': 'key',
            'word2_en': 'muscle'
        },
        {
            'bin': '1',
            'choice1': '1 (strongly disagree)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (strongly agree)',
            'question_id': '',
            'question_prompt_post': '',
            'question_prompt_pre': 'Please answer the following question:',
            'question_type': 'catch',
            'trial_num': 27,
            'word': 'Squares have four sides',
            'word1_en': '',
            'word2_en': ''
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '70',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 28,
            'word': 'lonely vs passion',
            'word1_en': 'lonely',
            'word2_en': 'passion'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '44',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 29,
            'word': 'glove vs cloud',
            'word1_en': 'glove',
            'word2_en': 'cloud'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '71',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 30,
            'word': 'snail vs baseball',
            'word1_en': 'snail',
            'word2_en': 'baseball'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '52',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 31,
            'word': 'bike vs morning',
            'word1_en': 'bike',
            'word2_en': 'morning'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '20',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 32,
            'word': 'editor vs knots',
            'word1_en': 'editor',
            'word2_en': 'knots'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '41',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 33,
            'word': 'deep vs granddaughter',
            'word1_en': 'deep',
            'word2_en': 'granddaughter'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '66',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 34,
            'word': 'special vs terminate',
            'word1_en': 'special',
            'word2_en': 'terminate'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '54',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 35,
            'word': ' morning vs  lip',
            'word1_en': ' morning',
            'word2_en': ' lip'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '59',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 36,
            'word': 'collect  vs emotion',
            'word1_en': 'collect ',
            'word2_en': 'emotion'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '69',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 37,
            'word': 'flower vs fluffy',
            'word1_en': 'flower',
            'word2_en': 'fluffy'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '48',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 38,
            'word': 'pillow vs technology',
            'word1_en': 'pillow',
            'word2_en': 'technology'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '67',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 39,
            'word': 'precious vs intertwine',
            'word1_en': 'precious',
            'word2_en': 'intertwine'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '15',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 40,
            'word': 'mundane world vs soil',
            'word1_en': 'mundane world',
            'word2_en': 'soil'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '8',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 41,
            'word': 'control vs hand shake',
            'word1_en': 'control',
            'word2_en': 'hand shake'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '7',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 42,
            'word': 'meditation vs dim',
            'word1_en': 'meditation',
            'word2_en': 'dim'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '56',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 43,
            'word': 'seaweed  vs nervous',
            'word1_en': 'seaweed ',
            'word2_en': 'nervous'
        },
        {
            'bin': '1',
            'choice1': '1 (strongly disagree)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (strongly agree)',
            'question_id': '',
            'question_prompt_post': '',
            'question_prompt_pre': 'Please answer the following question:',
            'question_type': 'catch',
            'trial_num': 44,
            'word': 'The word red has two letters',
            'word1_en': '',
            'word2_en': ''
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '11',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 45,
            'word': 'worry vs door',
            'word1_en': 'worry',
            'word2_en': 'door'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '32',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 46,
            'word': 'computer vs breeze',
            'word1_en': 'computer',
            'word2_en': 'breeze'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '74',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 47,
            'word': 'explain vs population',
            'word1_en': 'explain',
            'word2_en': 'population'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '34',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 48,
            'word': 'number vs serene',
            'word1_en': 'number',
            'word2_en': 'serene'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '79',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 49,
            'word': 'wall vs cup',
            'word1_en': 'wall',
            'word2_en': 'cup'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '14',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 50,
            'word': 'disaster vs burn',
            'word1_en': 'disaster',
            'word2_en': 'burn'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '29',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 51,
            'word': 'lead  vs cattle',
            'word1_en': 'lead ',
            'word2_en': 'cattle'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '39',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 52,
            'word': 'poison vs sea',
            'word1_en': 'poison',
            'word2_en': 'sea'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '17',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 53,
            'word': 'worship vs mountain',
            'word1_en': 'worship',
            'word2_en': 'mountain'
        },
        {
            'bin': '1',
            'choice1': '1 (strongly disagree)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (strongly agree)',
            'question_id': '',
            'question_prompt_post': '',
            'question_prompt_pre': 'Please answer the following question:',
            'question_type': 'catch',
            'trial_num': 54,
            'word': '6 is larger than 5',
            'word1_en': '',
            'word2_en': ''
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '3',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 55,
            'word': 'quilt vs skin',
            'word1_en': 'quilt',
            'word2_en': 'skin'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '75',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 56,
            'word': 'midnight vs chopstick',
            'word1_en': 'midnight',
            'word2_en': 'chopstick'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '47',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 57,
            'word': 'future vs cloud',
            'word1_en': 'future',
            'word2_en': 'cloud'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '16',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 58,
            'word': 'rich vs grain',
            'word1_en': 'rich',
            'word2_en': 'grain'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '40',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 59,
            'word': 'brutal vs baseball',
            'word1_en': 'brutal',
            'word2_en': 'baseball'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '4',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 60,
            'word': 'understand vs sun',
            'word1_en': 'understand',
            'word2_en': 'sun'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '18',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 61,
            'word': 'spirit vs grain',
            'word1_en': 'spirit',
            'word2_en': 'grain'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '21',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 62,
            'word': 'analysis vs knife',
            'word1_en': 'analysis',
            'word2_en': 'knife'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '5',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 63,
            'word': 'law vs water level',
            'word1_en': 'law',
            'word2_en': 'water level'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '65',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 64,
            'word': 'float vs neat',
            'word1_en': 'float',
            'word2_en': 'neat'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '63',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 65,
            'word': 'long-lasting vs imitate',
            'word1_en': 'long-lasting',
            'word2_en': 'imitate'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '68',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 66,
            'word': 'tremble vs spacious',
            'word1_en': 'tremble',
            'word2_en': 'spacious'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '60',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 67,
            'word': 'shower vs  valley',
            'word1_en': 'shower',
            'word2_en': ' valley'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '19',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 68,
            'word': 'thought vs footprint',
            'word1_en': 'thought',
            'word2_en': 'footprint'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '58',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 69,
            'word': 'call  vs sea',
            'word1_en': 'call ',
            'word2_en': 'sea'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '57',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 70,
            'word': ' type  vs rice',
            'word1_en': ' type ',
            'word2_en': 'rice'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '35',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 71,
            'word': 'fishhook vs salute',
            'word1_en': 'fishhook',
            'word2_en': 'salute'
        },
        {
            'bin': '1',
            'choice1': '1 (strongly disagree)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (strongly agree)',
            'question_id': '',
            'question_prompt_post': '',
            'question_prompt_pre': 'Please answer the following question:',
            'question_type': 'catch',
            'trial_num': 72,
            'word': 'triangles have three sides',
            'word1_en': '',
            'word2_en': ''
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '50',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 73,
            'word': 'king vs sandy soil',
            'word1_en': 'king',
            'word2_en': 'sandy soil'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '55',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 74,
            'word': 'conference vs  cloudy',
            'word1_en': 'conference',
            'word2_en': ' cloudy'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '31',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 75,
            'word': 'expert vs dolphin',
            'word1_en': 'expert',
            'word2_en': 'dolphin'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '42',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 76,
            'word': 'donkey vs enlightment',
            'word1_en': 'donkey',
            'word2_en': 'enlightment'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '64',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 77,
            'word': 'fixed vs cold',
            'word1_en': 'fixed',
            'word2_en': 'cold'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '37',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 78,
            'word': 'moss vs hail',
            'word1_en': 'moss',
            'word2_en': 'hail'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '72',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 79,
            'word': 'information vs snowflake',
            'word1_en': 'information',
            'word2_en': 'snowflake'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '1',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 80,
            'word': 'melancholy vs autumn',
            'word1_en': 'melancholy',
            'word2_en': 'autumn'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '73',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 81,
            'word': 'sad vs dry',
            'word1_en': 'sad',
            'word2_en': 'dry'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '80',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_language',
            'trial_num': 82,
            'word': 'ruler vs glove',
            'word1_en': 'ruler',
            'word2_en': 'glove'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '22',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'critical',
            'trial_num': 83,
            'word': 'accumulation vs field',
            'word1_en': 'accumulation',
            'word2_en': 'field'
        },
        {
            'bin': '1',
            'choice1': '1 (very different)',
            'choice2': '2',
            'choice3': '3',
            'choice4': '4',
            'choice5': '5',
            'choice6': '6',
            'choice7': '7 (very similar)',
            'question_id': '33',
            'question_prompt_post': '',
            'question_prompt_pre': 'How similar are these words?',
            'question_type': 'control_shape',
            'trial_num': 84,
            'word': 'chandelier  vs tranquil',
            'word1_en': 'chandelier ',
            'word2_en': 'tranquil'
        }
    ],
    'worker_id': 'test_worker_pytest'
}

snapshots['test_trials 2'] = '''trial_num,word,question_prompt_pre,question_prompt_post,question_type,bin,choice1,choice2,choice3,choice4,choice5,choice6,choice7,word1_en,word2_en,question_id
1,body vs capital,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),body,capital,25
2,cypress vs sun,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),cypress,sun,49
3,unsophisticated vs wood,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),unsophisticated,wood,27
4,attachment vs stretch,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),attachment,stretch,76
5,boost vs offer,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),boost,offer,10
6,handsome vs quiet,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),handsome,quiet,77
7,general vs float,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),general,float,30
8,sofa vs change,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),sofa,change,45
9,chair vs river,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),chair,river,38
10,hurt vs guess,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),hurt,guess,61
11,cloudy vs moon,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),cloudy,moon,2
12,covenant vs knife,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),covenant,knife,12
13,comb vs cultivate,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),comb,cultivate,43
14,forthright vs stone,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),forthright,stone,9
15,frequently vs step,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),frequently,step,24
16,fat vs lamp,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),fat,lamp,78
17,run vs ugly,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),run,ugly,62
18,miscellaneous vs silk thread,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),miscellaneous,silk thread,28
19,basic vs soil,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),basic,soil,23
20,science vs rent,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),science,rent,46
21,rigid vs woods,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),rigid,woods,6
22,adopt vs grasp,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),adopt,grasp,13
23, basic  vs china bowl,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar), basic ,china bowl,53
24,levels vs cloud,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),levels,cloud,26
25,literature vs neat,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),literature,neat,51
26,key vs muscle,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),key,muscle,36
27,Squares have four sides,Please answer the following question:,,catch,1,1 (strongly disagree),2,3,4,5,6,7 (strongly agree),,,
28,lonely vs passion,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),lonely,passion,70
29,glove vs cloud,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),glove,cloud,44
30,snail vs baseball,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),snail,baseball,71
31,bike vs morning,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),bike,morning,52
32,editor vs knots,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),editor,knots,20
33,deep vs granddaughter,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),deep,granddaughter,41
34,special vs terminate,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),special,terminate,66
35, morning vs  lip,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar), morning, lip,54
36,collect  vs emotion,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),collect ,emotion,59
37,flower vs fluffy,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),flower,fluffy,69
38,pillow vs technology,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),pillow,technology,48
39,precious vs intertwine,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),precious,intertwine,67
40,mundane world vs soil,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),mundane world,soil,15
41,control vs hand shake,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),control,hand shake,8
42,meditation vs dim,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),meditation,dim,7
43,seaweed  vs nervous,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),seaweed ,nervous,56
44,The word red has two letters,Please answer the following question:,,catch,1,1 (strongly disagree),2,3,4,5,6,7 (strongly agree),,,
45,worry vs door,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),worry,door,11
46,computer vs breeze,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),computer,breeze,32
47,explain vs population,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),explain,population,74
48,number vs serene,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),number,serene,34
49,wall vs cup,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),wall,cup,79
50,disaster vs burn,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),disaster,burn,14
51,lead  vs cattle,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),lead ,cattle,29
52,poison vs sea,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),poison,sea,39
53,worship vs mountain,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),worship,mountain,17
54,6 is larger than 5,Please answer the following question:,,catch,1,1 (strongly disagree),2,3,4,5,6,7 (strongly agree),,,
55,quilt vs skin,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),quilt,skin,3
56,midnight vs chopstick,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),midnight,chopstick,75
57,future vs cloud,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),future,cloud,47
58,rich vs grain,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),rich,grain,16
59,brutal vs baseball,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),brutal,baseball,40
60,understand vs sun,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),understand,sun,4
61,spirit vs grain,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),spirit,grain,18
62,analysis vs knife,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),analysis,knife,21
63,law vs water level,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),law,water level,5
64,float vs neat,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),float,neat,65
65,long-lasting vs imitate,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),long-lasting,imitate,63
66,tremble vs spacious,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),tremble,spacious,68
67,shower vs  valley,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),shower, valley,60
68,thought vs footprint,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),thought,footprint,19
69,call  vs sea,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),call ,sea,58
70, type  vs rice,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar), type ,rice,57
71,fishhook vs salute,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),fishhook,salute,35
72,triangles have three sides,Please answer the following question:,,catch,1,1 (strongly disagree),2,3,4,5,6,7 (strongly agree),,,
73,king vs sandy soil,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),king,sandy soil,50
74,conference vs  cloudy,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),conference, cloudy,55
75,expert vs dolphin,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),expert,dolphin,31
76,donkey vs enlightment,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),donkey,enlightment,42
77,fixed vs cold,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),fixed,cold,64
78,moss vs hail,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),moss,hail,37
79,information vs snowflake,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),information,snowflake,72
80,melancholy vs autumn,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),melancholy,autumn,1
81,sad vs dry,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),sad,dry,73
82,ruler vs glove,How similar are these words?,,control_language,1,1 (very different),2,3,4,5,6,7 (very similar),ruler,glove,80
83,accumulation vs field,How similar are these words?,,critical,1,1 (very different),2,3,4,5,6,7 (very similar),accumulation,field,22
84,chandelier  vs tranquil,How similar are these words?,,control_shape,1,1 (very different),2,3,4,5,6,7 (very similar),chandelier ,tranquil,33
'''

snapshots['test_trials 3'] = '''triallist_2 copy.csv,triallist_2.csv
0,0
1,0
'''

snapshots['test_trials 4'] = '''key,value
curr_batch_num,1
max_batch_num,
completed_batches,['triallist_2 copy.csv']
'''

snapshots['test_trials 5'] = '''key,value
curr_batch_num,2
max_batch_num,
completed_batches,"[\'triallist_2 copy.csv\', \'triallist_2.csv\']"
'''
