# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_randomize_trials 1'] = [
    {
        'condition': 'english_term',
        'distractor1': 'lions',
        'distractor2': 'eagles',
        'distractor3': 'clouds',
        'distractor4': 'desk',
        'distractor5': 'knife',
        'distractor6': 'river',
        'implicit_term': 'pests',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'fleas',
        'target2': 'mice',
        'target3': 'mosquitos'
    },
    {
        'condition': 'english_term',
        'distractor1': 'hamburger',
        'distractor2': 'broccoli',
        'distractor3': 'computer programming',
        'distractor4': 'blocks',
        'distractor5': 'ceramics',
        'distractor6': 'leaves',
        'implicit_term': 'appetizers',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'french fries',
        'target2': 'onion rings',
        'target3': 'chicken wings'
    },
    {
        'condition': 'english_term',
        'distractor1': 'lying',
        'distractor2': 'being late',
        'distractor3': 'boat',
        'distractor4': 'pillow',
        'distractor5': 'popcorn',
        'distractor6': 'moth',
        'implicit_term': 'crimes',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'murder',
        'target2': 'robbery',
        'target3': 'trespassing'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'sofa',
        'distractor2': 'bed',
        'distractor3': 'salt',
        'distractor4': 'clouds',
        'distractor5': 'wine',
        'distractor6': 'grass',
        'implicit_term': '电器',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'cell phone',
        'target2': 'microwave',
        'target3': 'TV'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'toilet',
        'distractor2': 'bathtub',
        'distractor3': 'chicken',
        'distractor4': 'tree',
        'distractor5': 'reservoir',
        'distractor6': 'pencil',
        'implicit_term': '家具',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'overhead light',
        'target2': 'bed',
        'target3': 'refrigerator'
    },
    {
        'condition': 'english_term',
        'distractor1': 'soy sauce',
        'distractor2': 'gasoline',
        'distractor3': 'truck',
        'distractor4': 'planet',
        'distractor5': 'flowers',
        'distractor6': 'hail',
        'implicit_term': 'beverages',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'coffee',
        'target2': 'beer',
        'target3': 'tea'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'flour',
        'distractor2': 'eggs',
        'distractor3': 'walrus',
        'distractor4': 'notepad',
        'distractor5': 'carpentry',
        'distractor6': 'snow',
        'implicit_term': '调味品',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'pepper',
        'target2': 'sugar',
        'target3': 'soy sauce'
    },
    {
        'condition': 'english_term',
        'distractor1': 'doll',
        'distractor2': 'balloon',
        'distractor3': 'apple slices',
        'distractor4': 'carpentry',
        'distractor5': 'computer',
        'distractor6': 'beer',
        'implicit_term': 'vehicles',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'boat',
        'target2': 'bus',
        'target3': 'tractor'
    },
    {
        'condition': 'english_term',
        'distractor1': 'oil',
        'distractor2': 'vinegar',
        'distractor3': 'motorcycle',
        'distractor4': 'star',
        'distractor5': 'tree',
        'distractor6': 'sleet',
        'implicit_term': 'beverages',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'wine',
        'target2': 'water',
        'target3': 'juice'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'eyeliner',
        'distractor2': 'shampoo',
        'distractor3': 'salt',
        'distractor4': 'car',
        'distractor5': 'hamburger',
        'distractor6': 'grapefruit',
        'implicit_term': '服饰',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'purse',
        'target2': 'coat',
        'target3': 'shirt'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'waterfall',
        'distractor2': 'starry sky',
        'distractor3': 'cheese',
        'distractor4': 'bowl',
        'distractor5': 'theft',
        'distractor6': 'hat',
        'implicit_term': '地形',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'lake',
        'target2': 'basin',
        'target3': 'highland'
    },
    {
        'condition': 'english_term',
        'distractor1': 'bluffing',
        'distractor2': 'spitting',
        'distractor3': 'bus',
        'distractor4': 'bed',
        'distractor5': 'carrots',
        'distractor6': 'monkey',
        'implicit_term': 'crimes',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'assault',
        'target2': 'rape',
        'target3': 'speeding'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'sandwich',
        'distractor2': 'pizza',
        'distractor3': 'deer',
        'distractor4': 'computer',
        'distractor5': 'sculpture',
        'distractor6': 'sleet',
        'implicit_term': '农产品',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'corn',
        'target2': 'vegetables',
        'target3': 'livestock'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'chicken',
        'distractor2': 'cheese',
        'distractor3': 'boat',
        'distractor4': 'clouds',
        'distractor5': 'painting',
        'distractor6': 'chair',
        'implicit_term': '调味品',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'salt',
        'target2': 'oyster sauce',
        'target3': 'cinnamon'
    },
    {
        'condition': 'english_term',
        'distractor1': 'ballet',
        'distractor2': 'poetry',
        'distractor3': 'boat',
        'distractor4': 'grass',
        'distractor5': 'moon',
        'distractor6': 'rain',
        'implicit_term': 'crafts',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'carpentry',
        'target2': 'knitting',
        'target3': 'painting'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'garden',
        'distractor2': 'sunrise',
        'distractor3': 'yogurt',
        'distractor4': 'rabbit',
        'distractor5': 'rape',
        'distractor6': 'bicycle',
        'implicit_term': '地形',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'river',
        'target2': 'plateau',
        'target3': 'mountains'
    },
    {
        'condition': 'english_term',
        'distractor1': 'clouds',
        'distractor2': 'lake',
        'distractor3': 'stove',
        'distractor4': 'deer',
        'distractor5': 'rice',
        'distractor6': 'notepad',
        'implicit_term': 'precipitation',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'hail',
        'target2': 'fog',
        'target3': 'drizzle'
    },
    {
        'condition': 'english_term',
        'distractor1': 'steak',
        'distractor2': 'pepperoni pizza',
        'distractor3': 'cooking',
        'distractor4': 'doll',
        'distractor5': 'sewing',
        'distractor6': 'bark',
        'implicit_term': 'appetizers',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'soup',
        'target2': 'salad',
        'target3': 'breadsticks'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'rain',
        'distractor2': 'soda',
        'distractor3': 'mountain',
        'distractor4': 'chicken',
        'distractor5': 'train',
        'distractor6': 'knife',
        'implicit_term': '水域',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'creek',
        'target2': 'pond',
        'target3': 'glacier'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'wall',
        'distractor2': 'house',
        'distractor3': 'salt',
        'distractor4': 'clouds',
        'distractor5': 'knife',
        'distractor6': 'coat',
        'implicit_term': '家具',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'carpet',
        'target2': 'sofa',
        'target3': 'curtains'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'cookies',
        'distractor2': 'ice cream',
        'distractor3': 'snake',
        'distractor4': 'pencil',
        'distractor5': 'knitting',
        'distractor6': 'rain',
        'implicit_term': '农产品',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'wheat',
        'target2': 'milk',
        'target3': 'beef'
    },
    {
        'condition': 'english_term',
        'distractor1': 'clouds',
        'distractor2': 'sparkling water',
        'distractor3': 'chopsticks',
        'distractor4': 'walrus',
        'distractor5': 'chocolate bar',
        'distractor6': 'pencil',
        'implicit_term': 'precipitation',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'rain',
        'target2': 'snow',
        'target3': 'sleet'
    },
    {
        'condition': 'english_term',
        'distractor1': 'drinking',
        'distractor2': 'going to school',
        'distractor3': 'cookies',
        'distractor4': 'water',
        'distractor5': 'planet',
        'distractor6': 'baseball',
        'implicit_term': 'skills',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'communication',
        'target2': 'singing',
        'target3': 'typing'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'snow',
        'distractor2': 'beer',
        'distractor3': 'valley',
        'distractor4': 'tomatoes',
        'distractor5': 'bus',
        'distractor6': 'chair',
        'implicit_term': '水域',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'river',
        'target2': 'reservoir',
        'target3': 'sea'
    },
    {
        'condition': 'english_term',
        'distractor1': 'music',
        'distractor2': 'literature',
        'distractor3': 'bus',
        'distractor4': 'seeds',
        'distractor5': 'sun',
        'distractor6': 'snow',
        'implicit_term': 'crafts',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'sculpture',
        'target2': 'sewing',
        'target3': 'ceramics'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'lipstick',
        'distractor2': 'soap',
        'distractor3': 'tree',
        'distractor4': 'roasted duck',
        'distractor5': 'hills',
        'distractor6': 'sandwich',
        'implicit_term': '服饰',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'ring',
        'target2': 'hat',
        'target3': 'shorts'
    },
    {
        'condition': 'english_term',
        'distractor1': 'potassium',
        'distractor2': 'sodium',
        'distractor3': 'banana',
        'distractor4': 'carpentry',
        'distractor5': 'cup',
        'distractor6': 'lamp',
        'implicit_term': 'drugs',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'aspirin',
        'target2': 'cocaine',
        'target3': 'marijuana'
    },
    {
        'condition': 'english_term',
        'distractor1': 'eating',
        'distractor2': 'walking',
        'distractor3': 'chips',
        'distractor4': 'wine',
        'distractor5': 'star',
        'distractor6': 'stuffed animal',
        'implicit_term': 'skills',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'cooking',
        'target2': 'computer programming',
        'target3': 'teamwork'
    },
    {
        'condition': 'english_term',
        'distractor1': 'blocks',
        'distractor2': 'legos',
        'distractor3': 'peanuts',
        'distractor4': 'knitting',
        'distractor5': 'television',
        'distractor6': 'tea',
        'implicit_term': 'vehicles',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'train',
        'target2': 'car',
        'target3': 'spaceship'
    },
    {
        'condition': 'english_term',
        'distractor1': 'giraffes',
        'distractor2': 'ducks',
        'distractor3': 'sky',
        'distractor4': 'chair',
        'distractor5': 'spoon',
        'distractor6': 'ocean',
        'implicit_term': 'pests',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'ants',
        'target2': 'rats',
        'target3': 'raccoons'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'face wash',
        'distractor2': 'bubble bath',
        'distractor3': 'yogurt',
        'distractor4': 'grass',
        'distractor5': 'lake',
        'distractor6': 'forest',
        'implicit_term': '化妆品',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'eyeliner',
        'target2': 'eye cream',
        'target3': 'moisturizer'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'chair',
        'distractor2': 'pillow',
        'distractor3': 'chicken',
        'distractor4': 'tree',
        'distractor5': 'juice',
        'distractor6': 'garden',
        'implicit_term': '电器',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'computer',
        'target2': 'air conditioner',
        'target3': 'table lamp'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'mineral',
        'distractor2': 'river',
        'distractor3': 'baseball',
        'distractor4': 'boat',
        'distractor5': 'chair',
        'distractor6': 'earrings',
        'implicit_term': '生物',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'animal',
        'target2': 'insect',
        'target3': 'virus'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'soil',
        'distractor2': 'land',
        'distractor3': 'cheese',
        'distractor4': 'chair',
        'distractor5': 'cocaine',
        'distractor6': 'boat',
        'implicit_term': '风景',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'lake',
        'target2': 'forest',
        'target3': 'ancient city'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'shampoo',
        'distractor2': 'tampon',
        'distractor3': 'carrots',
        'distractor4': 'tree',
        'distractor5': 'chair',
        'distractor6': 'ancient city',
        'implicit_term': '化妆品',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'lipstick',
        'target2': 'lotion',
        'target3': 'blush'
    },
    {
        'condition': 'english_term',
        'distractor1': 'vitamins',
        'distractor2': 'ammonia',
        'distractor3': 'grapefruit',
        'distractor4': 'knitting',
        'distractor5': 'bowl',
        'distractor6': 'table',
        'implicit_term': 'drugs',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'heroin',
        'target2': 'caffeine',
        'target3': 'methamphetamine'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'rock',
        'distractor2': 'tree',
        'distractor3': 'yogurt',
        'distractor4': 'stove',
        'distractor5': 'LSD',
        'distractor6': 'truck',
        'implicit_term': '风景',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'mountains',
        'target2': 'desert',
        'target3': 'starry sky'
    },
    {
        'condition': 'english_term',
        'distractor1': 'spaghetti',
        'distractor2': 'salad',
        'distractor3': 'bear',
        'distractor4': 'paper',
        'distractor5': 'teamwork',
        'distractor6': 'fog',
        'implicit_term': 'snacks',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'chips',
        'target2': 'cookies',
        'target3': 'apple slices'
    },
    {
        'condition': 'chinese_term',
        'distractor1': 'stone',
        'distractor2': 'mountain',
        'distractor3': 'computer programming',
        'distractor4': 'motorcycle',
        'distractor5': 'barrette',
        'distractor6': 'microphone',
        'implicit_term': '生物',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'plant',
        'target2': 'fungus',
        'target3': 'human'
    },
    {
        'condition': 'english_term',
        'distractor1': 'steak',
        'distractor2': 'salmon',
        'distractor3': 'snake',
        'distractor4': 'pen',
        'distractor5': 'communication',
        'distractor6': 'drizzle',
        'implicit_term': 'snacks',
        'language': 'english',
        'order': '1',
        'question_type': '',
        'target1': 'peanuts',
        'target2': 'popcorn',
        'target3': 'carrots'
    }
]
