# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_trials 1'] = {
    'completed_demographics': False,
    'consent_agreed': False,
    'num_trials': 24,
    'trials': [
        {
            'A': 'Rounded figures that form some type of head circular rounded head shape.',
            'B': "Abstract lines that don't have a defined head shape.",
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A1969Q0R4Y0E3J',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 1
        },
        {
            'A': 'These shapes are pointing up and to the left.',
            'B': 'These shapes are pointing to the right.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A2SY0XL28MLUTW',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 2
        },
        {
            'A': 'These are more like blobs that have a sharp indentation in them almost like a mouth.',
            'B': 'They have a base at the bottom, and reminds me of a bird.',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'AQYYBOOF0846O',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 3
        },
        {
            'A': 'These shapes tend to be "fluffier" and have a few sharp, narrow sections and points to them.',
            'B': 'These shapes tend to have many narrow sections as well as sharp points and angles. They also tend to be skinnier and have less area.',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A2WVCXVSE0YGML',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 4
        },
        {
            'A': 'These shapes are more round and robust',
            'B': 'These shapes have sharper points and more distinct inlets',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A2OX8TSRCU6NKD',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 5
        },
        {
            'A': 'These shapes have many rounded edges.  They have large, curved appendages interspersed with deep "V\'s" cut into the shapes.  They have sharps points around the outside edge as well.  The points are sporadically placed in between the other two features.  Many resemble a Halloween ghost costume with their arms outstretched.',
            'B': 'These shapes have many sharp edges and squiggly edges as well.  They tend to have a large protuberance at the base which appears as either a large rounded bottom or a rounded-off triangle shape.   Many resemble a a magical genie lantern.',
            'label_cond': '1',
            'left': 'A',
            'ppt_ID': 'A2FZBKFL7SCHHL',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 6
        },
        {
            'A': 'they are more oval',
            'B': 'they have a sharp spike',
            'label_cond': '1',
            'left': 'A',
            'ppt_ID': 'A1C7XI68SED8JE',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 7
        },
        {
            'A': 'They all have a shape protruding from the right side',
            'B': 'They all have a shape protruding from the bottom',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A358YR7MWC6LRH',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 8
        },
        {
            'A': 'This group is more smooth than jagged',
            'B': 'This group is more jagged than smooth',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A2XKIP0PJ3FJ20',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 9
        },
        {
            'A': 'Every shape has a sharp rounded curve in the bottom-right part of the shape.',
            'B': 'Every shape either has a "beak" that looks like a bird\'s beak or it has a "pedestal" bottom that looks like a cake plate pedestal.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A3LVLZS8S41ZD7',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 10
        },
        {
            'A': 'Mostly rounded edges. More "curvy."',
            'B': 'Mostly contain sharp corner. More "pointy."',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A2TXZVXQU5FQZ9',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 11
        },
        {
            'A': 'These images have a blob near the bottom, but it extends more to the right of the image. Overall, these are more bulbous.',
            'B': 'These shapes have an appendage or blob that extends downwards of the bottom of the image. Some even have a pointed part of the right side of the image. Overall these images are also less bulbous than the images on the right.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A3HP7L563UF5DW',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 12
        },
        {
            'A': 'these shapes have a round edge on the right hand side',
            'B': 'these shapes have a pointy edge on the right hand ride',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A33UH0X5UT1QRH',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 13
        },
        {
            'A': 'These shapes seemed to all take on the characteristics of someone wearing a sheet on Halloween.',
            'B': 'These shapes tend to look like birds is flight with long beaks.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A3KU7DD8Q1NQ7P',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 14
        },
        {
            'A': 'The curves are wider, more open, like a C rather than a V.  They tend to look like various creatures.',
            'B': 'The curves are sharper, think V rather than C. They tend to look somewhat like birds.',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A3CH1Z6J9R38G9',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 15
        },
        {
            'A': 'These shapes have more rounded edges than the other group',
            'B': 'These shapes are more sharply edged than the other group',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'ADZHJZ078THWQ',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 16
        },
        {
            'A': 'These shapes all look like a flying animal such as a dragon or bird',
            'B': 'These shapes look like a sort of leaf that you would see in the fall or they could look like a pelican of some sort.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A2NUGRVI6IEGN7',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 17
        },
        {
            'A': 'These shapes kind of look like they have a head, body, wings and feet. They are very round with at most one sharp point.',
            'B': 'All of these shapes look like they are something on top of a stand. They can also look like a bird standing on the ground or a lamp. They also have a lot of very sharp points.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A318M33K2896OL',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 18
        },
        {
            'A': 'the beaks that they have are a little bit thicker and rounded',
            'B': 'the beak is very thin and points very straight ahead at times',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A23KAJRDVCVGOE',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 19
        },
        {
            'A': 'These shapes have a round part that protrudes from the front that resembles a head. They have a long slender body with two shapes that come out from the top that resemble wings.',
            'B': 'The shapes have a pedestal they sit upon. The front end sticks out into a distinct point. There is a bowl shape on the backside that is flat on the top.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A2GTJ0BD4CG1A2',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 20
        },
        {
            'A': 'circular tails on the right',
            'B': 'pointy tails on the right',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'AR4XFM7G1W0VQ',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 21
        },
        {
            'A': 'The right side of the shape is rounded with a concave shape.',
            'B': 'The shape has a triangular shaped projection from the lower section of the shape. It also has at least 2 pointed shapes coming out of it.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'AOFDUROJ8XRZT',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 22
        },
        {
            'A': 'These shapes tend to  have rounded shapes that are almost appendages',
            'B': 'these shapes tend to have a beak or pointy protrusion on its right hand side',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A2Y5I2HJTRFR8H',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 23
        },
        {
            'A': 'All these are ghosty boys',
            'B': 'All these have a spike on the lower left.',
            'label_cond': '1',
            'left': 'A',
            'ppt_ID': 'A3AUIYZ27TBTP9',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 24
        }
    ],
    'worker_id': 'test_worker_pytest'
}

snapshots['test_trials 2'] = '''trial_num,ppt_ID,label_cond,A,B,left,right,stimuli
1,A1969Q0R4Y0E3J,1,Rounded figures that form some type of head circular rounded head shape.,Abstract lines that don\'t have a defined head shape.,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
2,A2SY0XL28MLUTW,0,These shapes are pointing up and to the left.,These shapes are pointing to the right.,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
3,AQYYBOOF0846O,1,These are more like blobs that have a sharp indentation in them almost like a mouth.,"They have a base at the bottom, and reminds me of a bird.",B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
4,A2WVCXVSE0YGML,1,"These shapes tend to be ""fluffier"" and have a few sharp, narrow sections and points to them.",These shapes tend to have many narrow sections as well as sharp points and angles. They also tend to be skinnier and have less area.,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
5,A2OX8TSRCU6NKD,0,These shapes are more round and robust,These shapes have sharper points and more distinct inlets,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
6,A2FZBKFL7SCHHL,1,"These shapes have many rounded edges.  They have large, curved appendages interspersed with deep ""V\'s"" cut into the shapes.  They have sharps points around the outside edge as well.  The points are sporadically placed in between the other two features.  Many resemble a Halloween ghost costume with their arms outstretched.",These shapes have many sharp edges and squiggly edges as well.  They tend to have a large protuberance at the base which appears as either a large rounded bottom or a rounded-off triangle shape.   Many resemble a a magical genie lantern.,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
7,A1C7XI68SED8JE,1,they are more oval,they have a sharp spike,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
8,A358YR7MWC6LRH,1,They all have a shape protruding from the right side,They all have a shape protruding from the bottom,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
9,A2XKIP0PJ3FJ20,1,This group is more smooth than jagged,This group is more jagged than smooth,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
10,A3LVLZS8S41ZD7,0,Every shape has a sharp rounded curve in the bottom-right part of the shape.,"Every shape either has a ""beak"" that looks like a bird\'s beak or it has a ""pedestal"" bottom that looks like a cake plate pedestal.",A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
11,A2TXZVXQU5FQZ9,1,"Mostly rounded edges. More ""curvy.""","Mostly contain sharp corner. More ""pointy.""",B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
12,A3HP7L563UF5DW,0,"These images have a blob near the bottom, but it extends more to the right of the image. Overall, these are more bulbous.",These shapes have an appendage or blob that extends downwards of the bottom of the image. Some even have a pointed part of the right side of the image. Overall these images are also less bulbous than the images on the right.,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
13,A33UH0X5UT1QRH,0,these shapes have a round edge on the right hand side,these shapes have a pointy edge on the right hand ride,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
14,A3KU7DD8Q1NQ7P,0,These shapes seemed to all take on the characteristics of someone wearing a sheet on Halloween.,These shapes tend to look like birds is flight with long beaks.,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
15,A3CH1Z6J9R38G9,1,"The curves are wider, more open, like a C rather than a V.  They tend to look like various creatures.","The curves are sharper, think V rather than C. They tend to look somewhat like birds.",B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
16,ADZHJZ078THWQ,1,These shapes have more rounded edges than the other group,These shapes are more sharply edged than the other group,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
17,A2NUGRVI6IEGN7,0,These shapes all look like a flying animal such as a dragon or bird,These shapes look like a sort of leaf that you would see in the fall or they could look like a pelican of some sort.,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
18,A318M33K2896OL,0,"These shapes kind of look like they have a head, body, wings and feet. They are very round with at most one sharp point.",All of these shapes look like they are something on top of a stand. They can also look like a bird standing on the ground or a lamp. They also have a lot of very sharp points.,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
19,A23KAJRDVCVGOE,0,the beaks that they have are a little bit thicker and rounded,the beak is very thin and points very straight ahead at times,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
20,A2GTJ0BD4CG1A2,0,These shapes have a round part that protrudes from the front that resembles a head. They have a long slender body with two shapes that come out from the top that resemble wings.,The shapes have a pedestal they sit upon. The front end sticks out into a distinct point. There is a bowl shape on the backside that is flat on the top.,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
21,AR4XFM7G1W0VQ,1,circular tails on the right,pointy tails on the right,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
22,AOFDUROJ8XRZT,0,The right side of the shape is rounded with a concave shape.,The shape has a triangular shaped projection from the lower section of the shape. It also has at least 2 pointed shapes coming out of it.,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
23,A2Y5I2HJTRFR8H,0,These shapes tend to  have rounded shapes that are almost appendages,these shapes tend to have a beak or pointy protrusion on its right hand side,B,A,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
24,A3AUIYZ27TBTP9,1,All these are ghosty boys,All these have a spike on the lower left.,A,B,"[\'B_17.png\', \'A_28.png\', \'A_18.png\', \'A_7.png\', \'B_1.png\', \'A_9.png\', \'B_23.png\', \'B_24.png\', \'B_3.png\', \'A_26.png\', \'B_12.png\', \'A_27.png\', \'A_22.png\', \'B_21.png\', \'B_19.png\', \'A_1.png\', \'B_15.png\', \'A_25.png\', \'B_6.png\', \'A_19.png\']"
'''

snapshots['test_trials 3'] = {
    'completed_demographics': False,
    'consent_agreed': False,
    'num_trials': 24,
    'trials': [
        {
            'A': 'Rounded figures that form some type of head circular rounded head shape.',
            'B': "Abstract lines that don't have a defined head shape.",
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A1969Q0R4Y0E3J',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 1
        },
        {
            'A': 'These shapes are pointing up and to the left.',
            'B': 'These shapes are pointing to the right.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A2SY0XL28MLUTW',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 2
        },
        {
            'A': 'These are more like blobs that have a sharp indentation in them almost like a mouth.',
            'B': 'They have a base at the bottom, and reminds me of a bird.',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'AQYYBOOF0846O',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 3
        },
        {
            'A': 'These shapes tend to be "fluffier" and have a few sharp, narrow sections and points to them.',
            'B': 'These shapes tend to have many narrow sections as well as sharp points and angles. They also tend to be skinnier and have less area.',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A2WVCXVSE0YGML',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 4
        },
        {
            'A': 'These shapes are more round and robust',
            'B': 'These shapes have sharper points and more distinct inlets',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A2OX8TSRCU6NKD',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 5
        },
        {
            'A': 'These shapes have many rounded edges.  They have large, curved appendages interspersed with deep "V\'s" cut into the shapes.  They have sharps points around the outside edge as well.  The points are sporadically placed in between the other two features.  Many resemble a Halloween ghost costume with their arms outstretched.',
            'B': 'These shapes have many sharp edges and squiggly edges as well.  They tend to have a large protuberance at the base which appears as either a large rounded bottom or a rounded-off triangle shape.   Many resemble a a magical genie lantern.',
            'label_cond': '1',
            'left': 'A',
            'ppt_ID': 'A2FZBKFL7SCHHL',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 6
        },
        {
            'A': 'they are more oval',
            'B': 'they have a sharp spike',
            'label_cond': '1',
            'left': 'A',
            'ppt_ID': 'A1C7XI68SED8JE',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 7
        },
        {
            'A': 'They all have a shape protruding from the right side',
            'B': 'They all have a shape protruding from the bottom',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A358YR7MWC6LRH',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 8
        },
        {
            'A': 'This group is more smooth than jagged',
            'B': 'This group is more jagged than smooth',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A2XKIP0PJ3FJ20',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 9
        },
        {
            'A': 'Every shape has a sharp rounded curve in the bottom-right part of the shape.',
            'B': 'Every shape either has a "beak" that looks like a bird\'s beak or it has a "pedestal" bottom that looks like a cake plate pedestal.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A3LVLZS8S41ZD7',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 10
        },
        {
            'A': 'Mostly rounded edges. More "curvy."',
            'B': 'Mostly contain sharp corner. More "pointy."',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A2TXZVXQU5FQZ9',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 11
        },
        {
            'A': 'These images have a blob near the bottom, but it extends more to the right of the image. Overall, these are more bulbous.',
            'B': 'These shapes have an appendage or blob that extends downwards of the bottom of the image. Some even have a pointed part of the right side of the image. Overall these images are also less bulbous than the images on the right.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A3HP7L563UF5DW',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 12
        },
        {
            'A': 'these shapes have a round edge on the right hand side',
            'B': 'these shapes have a pointy edge on the right hand ride',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A33UH0X5UT1QRH',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 13
        },
        {
            'A': 'These shapes seemed to all take on the characteristics of someone wearing a sheet on Halloween.',
            'B': 'These shapes tend to look like birds is flight with long beaks.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A3KU7DD8Q1NQ7P',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 14
        },
        {
            'A': 'The curves are wider, more open, like a C rather than a V.  They tend to look like various creatures.',
            'B': 'The curves are sharper, think V rather than C. They tend to look somewhat like birds.',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'A3CH1Z6J9R38G9',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 15
        },
        {
            'A': 'These shapes have more rounded edges than the other group',
            'B': 'These shapes are more sharply edged than the other group',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'ADZHJZ078THWQ',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 16
        },
        {
            'A': 'These shapes all look like a flying animal such as a dragon or bird',
            'B': 'These shapes look like a sort of leaf that you would see in the fall or they could look like a pelican of some sort.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A2NUGRVI6IEGN7',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 17
        },
        {
            'A': 'These shapes kind of look like they have a head, body, wings and feet. They are very round with at most one sharp point.',
            'B': 'All of these shapes look like they are something on top of a stand. They can also look like a bird standing on the ground or a lamp. They also have a lot of very sharp points.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A318M33K2896OL',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 18
        },
        {
            'A': 'the beaks that they have are a little bit thicker and rounded',
            'B': 'the beak is very thin and points very straight ahead at times',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A23KAJRDVCVGOE',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 19
        },
        {
            'A': 'These shapes have a round part that protrudes from the front that resembles a head. They have a long slender body with two shapes that come out from the top that resemble wings.',
            'B': 'The shapes have a pedestal they sit upon. The front end sticks out into a distinct point. There is a bowl shape on the backside that is flat on the top.',
            'label_cond': '0',
            'left': 'A',
            'ppt_ID': 'A2GTJ0BD4CG1A2',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 20
        },
        {
            'A': 'circular tails on the right',
            'B': 'pointy tails on the right',
            'label_cond': '1',
            'left': 'B',
            'ppt_ID': 'AR4XFM7G1W0VQ',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 21
        },
        {
            'A': 'The right side of the shape is rounded with a concave shape.',
            'B': 'The shape has a triangular shaped projection from the lower section of the shape. It also has at least 2 pointed shapes coming out of it.',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'AOFDUROJ8XRZT',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 22
        },
        {
            'A': 'These shapes tend to  have rounded shapes that are almost appendages',
            'B': 'these shapes tend to have a beak or pointy protrusion on its right hand side',
            'label_cond': '0',
            'left': 'B',
            'ppt_ID': 'A2Y5I2HJTRFR8H',
            'right': 'A',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 23
        },
        {
            'A': 'All these are ghosty boys',
            'B': 'All these have a spike on the lower left.',
            'label_cond': '1',
            'left': 'A',
            'ppt_ID': 'A3AUIYZ27TBTP9',
            'right': 'B',
            'stimuli': [
                'B_17.png',
                'A_28.png',
                'A_18.png',
                'A_7.png',
                'B_1.png',
                'A_9.png',
                'B_23.png',
                'B_24.png',
                'B_3.png',
                'A_26.png',
                'B_12.png',
                'A_27.png',
                'A_22.png',
                'B_21.png',
                'B_19.png',
                'A_1.png',
                'B_15.png',
                'A_25.png',
                'B_6.png',
                'A_19.png'
            ],
            'trial_num': 24
        }
    ],
    'worker_id': 'test_worker_pytest'
}
